name: ğŸ Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: ğŸ€ Deploy
    steps:
      - uses: actions/checkout@master
      - name: ğŸ–¨ï¸ Publish
        uses: cloudflare/wrangler-action@1.0.0
        with:
          apiKey: ${{ secrets.apiKey }}
          email: ${{ secrets.email }}
